export const env = {
  API_URL: process.env.EXPO_PUBLIC_API_BASE_URL,
  CLERK_PUBLISHABLE_KEY: process.env.EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY,
  EXPO_PUBLIC_SENTRY_DSN: process.env.EXPO_PUBLIC_SENTRY_DSN,
  ENV: process.env.EXPO_PUBLIC_ENV,
};
